### ISSUE TITLE
Missing own-icons-template.css

### ISSUE THREAD

**Issue by tohagan** [tmaximini/generator-ionic-gulp#12]
The `iconfont` task it reports that `app/icons/own-icons-template.css` is not found

d:\Projects\MyProjsrc\client\node_modules\gulp-iconfont-css\index.js:104
                                                throw error;
                                                      ^
Error: ENOENT, open 'd:\Projects\MyProj\src\client\app\icons\own-icons-template.css'

How do I create this file or where do I find an example?

**Comment by tohagan** [comment]
I see that gulp-iconfont-css/README.md suggests we might be able to just default this path but I don't know if this template is what Ionic requires.

#### options.path

Type: `String`

The template path (optional, defaults to `css` template provided with plugin).If set to `'scss'` or `'less'`, the corresponding default template will be used. See [templates](templates)

**Comment by tmaximini** [comment]
hi,
I added the missing css template into `app/icons` - make sure you uncomment this from `index.html`

`<link rel="stylesheet" href="styles/own-icons.css">`
