### ISSUE TITLE
template html files are not removed in the apk file

### ISSUE THREAD

**Issue by odinixadmin** [tmaximini/generator-ionic-gulp#13]
akp/assets/www folder retains template files. Given that template cache is used, these templates should not be kept? script and css files are handled correctly. Excellent generator, thank you.

**Comment by tmaximini** [comment]
not sure what the consequences are if we delete those files. the `index.html` for example also lives in this folder. will test when I find the time, thanks.

**Comment by palpa** [comment]
Hi, this can be fixed removing the 'templates' gulp task. Using always the compiled version (templates.js) works great on browser and genymotion/device!

**Comment by palpa** [comment]
Also changing the emulate task to perform a run with livereload ('ionic run ' + emulate + ' --livereload --consolelogs'), the templates are correctly updated to genymotion/device when changed on app folder.  Thanks for your great generator!

**Comment by tmaximini** [comment]
hi palpa, thanks for chiming in. emulate with live reload sounds nice and easier than the current solution. I will look into that for a future release. Also I am thankful for any PRs that help to further improve the generator.

**Comment by tmaximini** [comment]
fixed in 1.4.0
