### ISSUE TITLE
Browserify support

### ISSUE THREAD

**Issue by Qwerios** [tmaximini/generator-ionic-gulp#16]
Howdy,

I've forked your excellent generator and added browserify support for my own dark purposes ;) Mostly for module structuring convention, npm based module support, and transpiling we need (es6, typescript, coffeescript, etc.).

My question to you is would you like me to create a pull request to add browserify support as an option for your generator or should I fork and publish my own (ie. generator-ionic-gulp-browserify). Making it an option will require a new set of application template files but it should be doable. Using browserify is quite a different and opinionated approach hence my question. Obviously full credit to your repo will be given should you prefer a fork.

I haven't pushed to my own github yet because your preference decides how I go forward with branching and merging. Looking forward to hearing from you.

**Comment by tmaximini** [comment]
hi @Qwerios 
I would definitely appreciate a PR as long as it will stay "opt-in" - so bascially you'll have to create an option during the yeoman questionaire and then scaffold out different templates. I am not very familiar with browserify (webpack here) but I think it might be a good step regarding the different compile-to-js-languages that we need to transpile in future. 
So yeah, definitely interested :+1:

**Comment by Qwerios** [comment]
Alright I'll get to work. Should hopefully be able to find some time in the coming days. I'll close this issue and make a separate pull request.
