### ISSUE TITLE
Windows cannot find 'Google chrome' Make sure you typed the name correctly and try again later ...

### ISSUE THREAD

**Issue by jahmani** [tmaximini/generator-ionic-gulp#2]
this line in gulpfile.js make a windows error
  open('http://localhost:' + port + '/', 'Google Chrome');
"Windows cannot find 'Google chrome' Make sure you typed the name correctly and try again later ... "
and for me can be fixed with removing the second parameter:
open('http://localhost:' + port + '/');
now gulp works with no errors

**Comment by tmaximini** [comment]
Hi @jahmani 
Thanks for reporting this, I did not test it on windows. I will add your fix asap.

**Comment by tmaximini** [comment]
fixed in 1.1.0

**Comment by jahmani** [comment]
thanks for your awesome library.
