### ISSUE TITLE
Generator not working

### ISSUE THREAD

**Issue by edthetechie** [tmaximini/generator-ionic-gulp#20]
I'm getting the following error when trying to install the generator, it was working fine until I updated nodejs and yo :-(

D:\Work Projects\STMobile>npm install -g generator-ionic-gulp
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
C:\Users\Ed\AppData\Roaming\npm
├── generator-ionic-gulp@1.3.3
└── UNMET PEER DEPENDENCY yo@>=1.0.0

npm WARN EPEERINVALID generator-ionic-gulp@1.3.3 requires a peer of yo@>=1.0.0 but none was installed.

**Comment by christianguevara** [comment]
Use

```
npm install -g yo
```

first.

Read instructions carefully :)

**Comment by edthetechie** [comment]
Yeah did that already... Obviously. Wouldn't have opened an issue without going through the steps a few times. Even tried installing the previous version of yo but with no joy. Here's the output from my console. If I missed something let me know.

```
D:\Work Projects\STMobile>npm install -g yo
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
C:\Users\Ed\AppData\Roaming\npm\yo -> C:\Users\Ed\AppData\Roaming\npm\node_modules\yo\lib\cli.js

> yo@1.5.0 postinstall C:\Users\Ed\AppData\Roaming\npm\node_modules\yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
√ npm version

Everything looks all right!
C:\Users\Ed\AppData\Roaming\npm
└── yo@1.5.0


D:\Work Projects\STMobile>npm install -g generator-ionic-gulp
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
C:\Users\Ed\AppData\Roaming\npm
├── generator-ionic-gulp@1.3.3
└── UNMET PEER DEPENDENCY yo@>=1.0.0

npm WARN EPEERINVALID generator-ionic-gulp@1.3.3 requires a peer of yo@>=1.0.0 but none was installed.
```

**Comment by christianguevara** [comment]
Sorry, not reading instructions is a common mistake.

I tried a clean install recently on Mac and it's working, seems like is not searching for yeoman (dependency) in the npm directory, maybe this can help [Cannot find installed module on windows](http://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows).

**Comment by tmaximini** [comment]
Hi Ed,
what's your installed npm version?
Your logs reminded me that I have to bump some dependencies.
I just reinstalled the generator on my machine and it worked fine with `npm 2.14.4` 
I know npm 3.x has issues with yeoman generators, so maybe there lays the problem.

**Comment by edthetechie** [comment]
I think you're right about the version, mine is:
    D:\Work Projects\STMobile>npm -v
    3.4.1
Uninstall and reinstall node with a lower version and see if that works

**Comment by tmaximini** [comment]
you don't need to change your node version. you can also install a specific npm version trhough npm iteself, e.g. `npm install -g npm@2.14.4`

**Comment by edthetechie** [comment]
Ah awesome, thanks! Am still a bit of a node noob :-)

**Comment by edthetechie** [comment]
That worked like magic. Thanks again for your help. I've already built one mobile app using the generator (was installing it all on a new PC) and I totally love the workflow :-)
