### ISSUE TITLE
Add support to wiredep to inject bower dependencies

### ISSUE THREAD

**Issue by nadouani** [tmaximini/generator-ionic-gulp#21]
It would be nice to add support for wiredep tool to make adding CSS and JS  dependencies easier.
Actually, using the vendor.json file is really not a convenient way.
BTW, how we can include bower dependencies CSS files?

Thanks

**Comment by tmaximini** [comment]
I had bad experience in the past with wiredep but I am open to give it another try. You are right that the vendor.json is not the most elegant way to handle things. 
For handling CSS imports I still use the old "save and rename to .scss and import" way - but there are other soulutions such as https://github.com/chriseppstein/sass-css-importer.

**Comment by JonathanWi** [comment]
Hey @tmaximini , great starter, but I do 100% agree with @nadouani regarding wiredep. Handling a vendor.json, which in turn is just a manual duplicate of bower.json just feels wrong.
Would it be possible to have the choice between both?

Thanks a lot

**Comment by tmaximini** [comment]
I'll look into it when I find the time - I also accept your Pull Requests if you have a working solution ;)

**Comment by tmaximini** [comment]
let me know if everything works for you with wiredep in 1.4.0

**Comment by nadouani** [comment]
Thanks, I'll give it a try

**Comment by JonathanWi** [comment]
Thanks, Same here, will keep you updated!
