### ISSUE TITLE
Running gulp on new app gives Sass executable error

### ISSUE THREAD

**Issue by henry74** [tmaximini/generator-ionic-gulp#3]
```
Error: Missing the Sass executable. Please install and make available on your PATH.
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

Perhaps add recommended way to install Sass to documentation?

**Comment by tmaximini** [comment]
Please make sure you have the ruby sass gem installed (I am using https://github.com/sindresorhus/gulp-ruby-sass here to compile .scss to .css).
`gem install sass` will do it. I will add it to the documentation.
