### ISSUE TITLE
Error when running gulp command

### ISSUE THREAD

**Issue by JayWIlsonJr** [tmaximini/generator-ionic-gulp#31]
After a fresh install, when I run the gulp command I get the follow error message:

```
$ ~/code/test-app: gulp
[07:49:58] Using gulpfile ~/code/test-app/gulpfile.js
[07:49:58] Starting 'default'...
[07:49:58] Starting 'clean'...
[07:49:58] Finished 'clean' after 5.38 ms
[07:49:58] Starting 'iconfont'...
[07:49:58] Finished 'iconfont' after 118 ms
[07:49:58] Starting 'fonts'...
[07:49:58] Starting 'styles'...
[07:49:58] Starting 'images'...
[07:49:58] Starting 'vendor'...
[07:49:58] Finished 'images' after 26 ms

events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: app/styles/ionic-styles.scss
Error: File to import not found or unreadable: bower_components/ionic/scss/ionic
       Parent style sheet: stdin
        on line 8 of stdin
>> @import 'bower_components/ionic/scss/ionic';
   ^

    at options.error (/Users/jaywilson/code/test-app/node_modules/node-sass/lib/index.js:277:32)
```

I am not seeing a bower_components folder which it is looking for?

Thanks

**Comment by tmaximini** [comment]
try running `bower install` manually in your project. At some point there should have been a bower install

**Comment by JayWIlsonJr** [comment]
When I run bower install it just returns me back to a empty prompt. There
is no message output, or files created. I tried that several times, the
bower_componets folder is still missing.



Jay Wilson Jr.

434-546-0911

[image: http://twitter.com/jaywilsonjr.com]@JayWilsonJr
<http://twitter.com/jaywilsonjr.com>
blog.JayWilsonJr.com <http://blog.jaywilsonjr.com/>
linkedin.com/in/jaywilsonjr

**Comment by JayWIlsonJr** [comment]
When I run `bower install` it just returns me back to a empty prompt. There
is no message output, or files created.

```
$ bower install
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
$ subl .
$ bower install
$
```

As you can see above on the initial run it tells me the name needs to be lowercase, so I changed the name to all lowercase in the bower.json file. After that I ran `bower install` again, but it just drops me back to a empty prompt.

Here's the contents of my bower.json file:

```
{
    "name": "test",
    "author": "Jay Wilson Jr. <jwilson@xxx.com>",
    "private": "true",
    "devDependencies": {},
    "dependencies": {
      "angular": "~1.4.8",
      "ngCordova": "~0.1.23-alpha",
      "angular-resource": "~1.4.8",
      "ionic": "~1.2.1"
    },
    "resolutions": {
    "angular": "1.4.8"
  }
}
```

**Comment by tmaximini** [comment]
I just npm installed the generator ans started a fresh project. after the npm install finishes it tries to automatically install bower deps. you should see some similar output:

![screen shot 2016-04-20 at 18 50 29](https://cloud.githubusercontent.com/assets/570544/14683032/e5545c5c-0728-11e6-8d10-1baa67e1ec5a.png)

can you try starting over in a fresh project?
it should also create a bower_components folder in the project root. if it does not, please add more info, like you node / npm versions, OS etc.

**Comment by tmaximini** [comment]
closed due to inactivity
