### ISSUE TITLE
confusion between src and scripts folder

### ISSUE THREAD

**Issue by david-aimi** [tmaximini/generator-ionic-gulp#34]
I tried looking through your documentation but I'm rather confused why you have both an SRC and scripts folder?  They appear to have the same / similar files.  It's probably something simple, but I'm having issues loading services, directives etc into the app via require module exports when adding in SRC folder. It's probably a novice mistake, but I don't understand the differences of the scripts vs src folder.  Thanks

**Comment by david-aimi** [comment]
FYI, I resolved this.  The problem was I originally had gulp-ionic-seed, and when i used the generator it overlapped.  I cleaned my entire project out and re-generated and it solved the issue.  I accidentally didn't start with a clean generator installation.

**Comment by tmaximini** [comment]
hey, glad you figured it out. The two projects are not 100% on par, that's why I recommend always using the generator to scaffold a new project.
