### ISSUE TITLE
PhoneGap Plugins?

### ISSUE THREAD

**Issue by talford** [tmaximini/generator-ionic-gulp#38]
So, pretty new to PhoneGap/Cordova... Using this generator, but cannot seem to figure out how to get the PhoneGap plugins to get built with this generator (or properly add to the build process). :/

**Comment by tmaximini** [comment]
what did you try? and which plugin are you trying to install, from my experience it is as easy as `ionic plugin add org.apache.cordova.camera` for example.
some plugins require additional install steps though.
