### ISSUE TITLE
use ionic.scss instead of ionic.min.css

### ISSUE THREAD

**Issue by trueter** [tmaximini/generator-ionic-gulp#4]
importing the minified css makes it impossible to use a custom .scss theme.
i tried streaming ionic.scss instead of ionic.min.css but get a ruby error
`
Error: Errno::ENOENT: No such file or directory @ rb_sysopen - /var/folders/l0/77cv0tbj11x6nd6g9_p0xgz80000gn/T/gulp-ruby-sass/ionic.css
`

**Comment by tmaximini** [comment]
hey trueter,
i will look into it. best thing would probably compile the ionic css together with our own during build.

**Comment by tmaximini** [comment]
@trueter please update to 1.2.0 and see if it works now

**Comment by trueter** [comment]
Works like a charm. 
I recommend using gulp-cache and gulp-remember around the compile step to get the re-compile time down from >2000 ms to ~100ms

```
.pipe(cache('ionic-sass'))
.pipe(sass(options))
.pipe(remember('ionic-sass'))
```

Thanks again!

**Comment by tmaximini** [comment]
thanks for the info, why not send a PR ;-)

**Comment by tmaximini** [comment]
added cached and remember via 113d6dc7967b22bb3cf5062cfce527ba774a0160

**Comment by trueter** [comment]
next time :)
