### ISSUE TITLE
Errors after a fresh install

### ISSUE THREAD

**Issue by sbatezat** [tmaximini/generator-ionic-gulp#8]
I've got two errors after a fresh install, using successfully the gulp command, on my chrome console:

http://localhost:9000/cordova.js Failed to load resource: the server responded with a status of 404 (Not Found)

vendor.js:4414 Uncaught Error: [$injector:unpr] Unknown provider: $$asyncCallbackProvider <- $$asyncCallback <- $animate <- $compile
http://errors.angularjs.org/1.4.3/$injector/unpr?p0=%24%24asyncCallbackProvider%20%3C-%20%24%24asyncCallback%20%3C-%20%24animate%20%3C-%20%24compile

**Comment by sbatezat** [comment]
Just fixed the second issue, it was related to the AngularJS version chosen on bower install. Indeed, when i'm doing bower install, i got that message:

Unable to find a suitable version for angular, please choose one:
    1) angular#1.3.13 which resolved to 1.3.13 and is required by angular-animate#1.3.13, angular-sanitize#1.3.13, ionic#1.0.1
    2) angular#>= 1.2.23 which resolved to 1.4.3 and is required by ngCordova#0.1.17-alpha
    3) angular#~1.4.0 which resolved to 1.4.3 and is required by 'my_app_name'
    4) angular#1.4.3 which resolved to 1.4.3 and is required by angular-resource#1.4.3
    5) angular#>= 1.0.8 which resolved to 1.4.3 and is required by angular-ui-router#0.2.13

I have chosen 1.4.0 the first time, and it was the cause of the issue. With 1.3.13, there is no error and everything seems to work fine. I think the bower.json file should contains that line to force the angular version to use:

"resolutions": {
  "angular": "1.3.13"
}

I still have an issue with cordova.js not found

**Comment by tmaximini** [comment]
Hi, thanks for the heads-up, I will look into the compatibility with angular 1.4.x

> I still have an issue with cordova.js not found

This is not an error. cordova.js will be generated once you build the project to a specific platform (e.g. `cordova build android` or using the gulp job `gulp -b`). While developing in the browser it is shown as missing, but this can be ignored.

**Comment by tmaximini** [comment]
I set the generator to default to angular 1.3.x for now, until Ionic officially supports Angular 1.4
